stages: 
  - backend        
  - build
  - test
  - deploy

backend:  
  stage: backend
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    #- echo "Stop the backend..."
    #- ssh -o StrictHostKeyChecking=no ubuntu@$DEPLOY_SERVER_IP "pkill java"
    #- echo "Stop complete."
    #- echo "Compiling the backend..."
    #- ssh -o StrictHostKeyChecking=no ubuntu@$DEPLOY_SERVER_IP 'cd grupo-04/'
    - ssh ubuntu@$DEPLOY_SERVER_IP 'cd grupo-04/; git pull'
    - ssh ubuntu@$DEPLOY_SERVER_IP 'cd grupo-04/; mvn package'
    #- echo "Compile complete."
    #- echo "Start the backend..."
    #- ssh ubuntu@$DEPLOY_SERVER_IP 'cd target/'
    - ssh ubuntu@$DEPLOY_SERVER_IP 'cd grupo-04/target; java -jar Grupo4-0.0.1-SNAPSHOT.jar &'
    - ssh ubuntu@$DEPLOY_SERVER_IP 'exit'
    #- echo "Start complete."
  rules:
    - when: manual 