stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  #when: manual
  image: node:latest
  script:
    - echo "Compiling the code..."
    - cd src/main/ui
    - npm install
    - npm run build
    - echo "Compile complete."
  artifacts:
    paths:
      - src/main/ui/build 
  rules:
    - when: manual 

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  #when: manual
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"
  needs: ["build-job"]

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  #when: manual
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - echo "Deploying application..."
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp src/main/ui/build s3://$S3_BUCKET --recursive
    - echo "Application successfully deployed."
  #needs: ["unit-test-job"]
  dependencies:
    - build-job
